### ISSUE TITLE
missing dependency on `yaml`

### ISSUE THREAD

**Issue by rwb27** [labthings/python-labthings#228]
**Describe the bug**
I think the published package should list `pyyaml` as a dependency

**To Reproduce**
```
from labthings import fields
```
This raised an `ImportError` because `pyyaml` wasn't installed

**Expected behaviour**
No errors

**Comment by jtc42** [comment]
Weird, that submodule doesn't seem to mention yaml anywhere. Could this be something upstream with Marshmallow? Or equally I might just be missing something stupid...

**Comment by rwb27** [comment]
My bad, I think it's a depenency problem:
```
Traceback (most recent call last):
  File ".\tests\find_extensions.py", line 11, in <module>
    loaded_plugins.append(p.load())
  File "C:\Users\rwb34\dev\ofm-extension-structure\.venv\lib\site-packages\importlib_metadata\__init__.py", line 167, in load
    module = import_module(match.group('module'))
line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\rwb34\dev\ofm-extension-structure\src\example_ofm_extension\extension.py", line 4, in <module>
    from labthings import fields
  File "C:\Users\rwb34\dev\ofm-extension-structure\.venv\lib\site-packages\labthings\__init__.py", line 21, in <module>
ne 8, in <module>
    from apispec_webframeworks.flask import FlaskPlugin
k.py", line 74, in <module>
  File "C:\Users\rwb34\dev\ofm-extension-structure\.venv\lib\site-packages\apispec\yaml_utils.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```
so I think `apispec` is the culprit.  Maybe there's an extra we missed?

**Comment by rwb27** [comment]
yes, I think we want to be depending on `apispec[yaml]`
