### ISSUE TITLE
marshall_task doesn't give helpful errors

### ISSUE THREAD

**Issue by jtc42** [labthings/python-labthings#28]
I accidentally left the ``@marshall_task`` decorator on a function that no longer returns a task - this produced the following:
```
[2020-03-24 16:23:48,307] [ThreadPoolExecutor-0_0] [ERROR] Exception on /api/v2/extensions/org.openflexure.calibration.picamera/flatten_lens_shading_table [POST]
Traceback (most recent call last):
  File "/var/openflexure/application/openflexure-microscope-server/.venv/src/labthings/labthings/server/sockets.py", line 38, in __call__
    handler, values = adapter.match()
  File "/var/openflexure/application/openflexure-microscope-server/.venv/lib/python3.7/site-packages/werkzeug/routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/openflexure/application/openflexure-microscope-server/.venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/openflexure/application/openflexure-microscope-server/.venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/openflexure/application/openflexure-microscope-server/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/var/openflexure/application/openflexure-microscope-server/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/var/openflexure/application/openflexure-microscope-server/.venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/openflexure/application/openflexure-microscope-server/.venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/var/openflexure/application/openflexure-microscope-server/.venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/openflexure/application/openflexure-microscope-server/.venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/openflexure/application/openflexure-microscope-server/.venv/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/var/openflexure/application/openflexure-microscope-server/.venv/src/labthings/labthings/server/view.py", line 53, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/var/openflexure/application/openflexure-microscope-server/.venv/src/labthings/labthings/server/decorators.py", line 91, in wrapper
    return make_response(TaskSchema().jsonify(resp))
  File "/var/openflexure/application/openflexure-microscope-server/.venv/src/labthings/labthings/server/schema.py", line 40, in jsonify
    data = self.dump(obj, many=many)
  File "/var/openflexure/application/openflexure-microscope-server/.venv/lib/python3.7/site-packages/marshmallow/schema.py", line 551, in dump
    PRE_DUMP, obj, many=many, original_data=obj
  File "/var/openflexure/application/openflexure-microscope-server/.venv/lib/python3.7/site-packages/marshmallow/schema.py", line 1066, in _invoke_dump_processors
    tag, pass_many=False, data=data, many=many, original_data=original_data
  File "/var/openflexure/application/openflexure-microscope-server/.venv/lib/python3.7/site-packages/marshmallow/schema.py", line 1224, in _invoke_processors
    data = processor(data, many=many, **kwargs)
  File "/var/openflexure/application/openflexure-microscope-server/.venv/src/labthings/labthings/server/schema.py", line 106, in generate_links
    "href": url_for(TASK_ENDPOINT, task_id=data.id, _external=True),
AttributeError: 'NoneType' object has no attribute 'id'
```

It would have been more helpful if it said "this function should return a task.  If it does not return a task, remove the @marshall_task decorator" or something...

**Comment by jtc42** [comment]
Closed by c6fe7147db99c4fa30d9501e1047b9c0c0db7f8d
